#pragma once

#include <typed-geometry/feature/basic.hh>

#include <typed-geometry/functions/objects/aabb.hh>
#include <typed-geometry/functions/objects/any_point.hh>
#include <typed-geometry/functions/objects/apex.hh>
#include <typed-geometry/functions/objects/area.hh>
#include <typed-geometry/functions/objects/boundary.hh>
#include <typed-geometry/functions/objects/bounds.hh>
#include <typed-geometry/functions/objects/centroid.hh>
#include <typed-geometry/functions/objects/closest_points.hh>
#include <typed-geometry/functions/objects/contains.hh>
#include <typed-geometry/functions/objects/coordinates.hh>
#include <typed-geometry/functions/objects/direction.hh>
#include <typed-geometry/functions/objects/distance.hh>
#include <typed-geometry/functions/objects/edges.hh>
#include <typed-geometry/functions/objects/faces.hh>
#include <typed-geometry/functions/objects/intersection.hh>
#include <typed-geometry/functions/objects/normal.hh>
#include <typed-geometry/functions/objects/perimeter.hh>
#include <typed-geometry/functions/objects/plane.hh>
#include <typed-geometry/functions/objects/project.hh>
#include <typed-geometry/functions/objects/rasterize.hh>
#include <typed-geometry/functions/objects/size.hh>
#include <typed-geometry/functions/objects/tangent.hh>
#include <typed-geometry/functions/objects/triangle.hh>
#include <typed-geometry/functions/objects/triangulate.hh>
#include <typed-geometry/functions/objects/triangulation.hh>
#include <typed-geometry/functions/objects/vertices.hh>
#include <typed-geometry/functions/objects/volume.hh>
