#pragma once

#include <typed-geometry/common/swizzling.hh>

// usage:
// using namespace tg::swizzling;
// v[xz] = {1, 2};

namespace tg::swizzling
{
inline constexpr swizzler<0, 0> xx;
inline constexpr swizzler<0, 1> xy;
inline constexpr swizzler<0, 2> xz;
inline constexpr swizzler<0, 3> xw;
inline constexpr swizzler<1, 0> yx;
inline constexpr swizzler<1, 1> yy;
inline constexpr swizzler<1, 2> yz;
inline constexpr swizzler<1, 3> yw;
inline constexpr swizzler<2, 0> zx;
inline constexpr swizzler<2, 1> zy;
inline constexpr swizzler<2, 2> zz;
inline constexpr swizzler<2, 3> zw;
inline constexpr swizzler<3, 0> wx;
inline constexpr swizzler<3, 1> wy;
inline constexpr swizzler<3, 2> wz;
inline constexpr swizzler<3, 3> ww;

inline constexpr swizzler<0, 0, 0> xxx;
inline constexpr swizzler<0, 0, 1> xxy;
inline constexpr swizzler<0, 0, 2> xxz;
inline constexpr swizzler<0, 0, 3> xxw;
inline constexpr swizzler<0, 1, 0> xyx;
inline constexpr swizzler<0, 1, 1> xyy;
inline constexpr swizzler<0, 1, 2> xyz;
inline constexpr swizzler<0, 1, 3> xyw;
inline constexpr swizzler<0, 2, 0> xzx;
inline constexpr swizzler<0, 2, 1> xzy;
inline constexpr swizzler<0, 2, 2> xzz;
inline constexpr swizzler<0, 2, 3> xzw;
inline constexpr swizzler<0, 3, 0> xwx;
inline constexpr swizzler<0, 3, 1> xwy;
inline constexpr swizzler<0, 3, 2> xwz;
inline constexpr swizzler<0, 3, 3> xww;
inline constexpr swizzler<1, 0, 0> yxx;
inline constexpr swizzler<1, 0, 1> yxy;
inline constexpr swizzler<1, 0, 2> yxz;
inline constexpr swizzler<1, 0, 3> yxw;
inline constexpr swizzler<1, 1, 0> yyx;
inline constexpr swizzler<1, 1, 1> yyy;
inline constexpr swizzler<1, 1, 2> yyz;
inline constexpr swizzler<1, 1, 3> yyw;
inline constexpr swizzler<1, 2, 0> yzx;
inline constexpr swizzler<1, 2, 1> yzy;
inline constexpr swizzler<1, 2, 2> yzz;
inline constexpr swizzler<1, 2, 3> yzw;
inline constexpr swizzler<1, 3, 0> ywx;
inline constexpr swizzler<1, 3, 1> ywy;
inline constexpr swizzler<1, 3, 2> ywz;
inline constexpr swizzler<1, 3, 3> yww;
inline constexpr swizzler<2, 0, 0> zxx;
inline constexpr swizzler<2, 0, 1> zxy;
inline constexpr swizzler<2, 0, 2> zxz;
inline constexpr swizzler<2, 0, 3> zxw;
inline constexpr swizzler<2, 1, 0> zyx;
inline constexpr swizzler<2, 1, 1> zyy;
inline constexpr swizzler<2, 1, 2> zyz;
inline constexpr swizzler<2, 1, 3> zyw;
inline constexpr swizzler<2, 2, 0> zzx;
inline constexpr swizzler<2, 2, 1> zzy;
inline constexpr swizzler<2, 2, 2> zzz;
inline constexpr swizzler<2, 2, 3> zzw;
inline constexpr swizzler<2, 3, 0> zwx;
inline constexpr swizzler<2, 3, 1> zwy;
inline constexpr swizzler<2, 3, 2> zwz;
inline constexpr swizzler<2, 3, 3> zww;
inline constexpr swizzler<3, 0, 0> wxx;
inline constexpr swizzler<3, 0, 1> wxy;
inline constexpr swizzler<3, 0, 2> wxz;
inline constexpr swizzler<3, 0, 3> wxw;
inline constexpr swizzler<3, 1, 0> wyx;
inline constexpr swizzler<3, 1, 1> wyy;
inline constexpr swizzler<3, 1, 2> wyz;
inline constexpr swizzler<3, 1, 3> wyw;
inline constexpr swizzler<3, 2, 0> wzx;
inline constexpr swizzler<3, 2, 1> wzy;
inline constexpr swizzler<3, 2, 2> wzz;
inline constexpr swizzler<3, 2, 3> wzw;
inline constexpr swizzler<3, 3, 0> wwx;
inline constexpr swizzler<3, 3, 1> wwy;
inline constexpr swizzler<3, 3, 2> wwz;
inline constexpr swizzler<3, 3, 3> www;

inline constexpr swizzler<0, 0, 0, 0> xxxx;
inline constexpr swizzler<0, 0, 0, 1> xxxy;
inline constexpr swizzler<0, 0, 0, 2> xxxz;
inline constexpr swizzler<0, 0, 0, 3> xxxw;
inline constexpr swizzler<0, 0, 1, 0> xxyx;
inline constexpr swizzler<0, 0, 1, 1> xxyy;
inline constexpr swizzler<0, 0, 1, 2> xxyz;
inline constexpr swizzler<0, 0, 1, 3> xxyw;
inline constexpr swizzler<0, 0, 2, 0> xxzx;
inline constexpr swizzler<0, 0, 2, 1> xxzy;
inline constexpr swizzler<0, 0, 2, 2> xxzz;
inline constexpr swizzler<0, 0, 2, 3> xxzw;
inline constexpr swizzler<0, 0, 3, 0> xxwx;
inline constexpr swizzler<0, 0, 3, 1> xxwy;
inline constexpr swizzler<0, 0, 3, 2> xxwz;
inline constexpr swizzler<0, 0, 3, 3> xxww;
inline constexpr swizzler<0, 1, 0, 0> xyxx;
inline constexpr swizzler<0, 1, 0, 1> xyxy;
inline constexpr swizzler<0, 1, 0, 2> xyxz;
inline constexpr swizzler<0, 1, 0, 3> xyxw;
inline constexpr swizzler<0, 1, 1, 0> xyyx;
inline constexpr swizzler<0, 1, 1, 1> xyyy;
inline constexpr swizzler<0, 1, 1, 2> xyyz;
inline constexpr swizzler<0, 1, 1, 3> xyyw;
inline constexpr swizzler<0, 1, 2, 0> xyzx;
inline constexpr swizzler<0, 1, 2, 1> xyzy;
inline constexpr swizzler<0, 1, 2, 2> xyzz;
inline constexpr swizzler<0, 1, 2, 3> xyzw;
inline constexpr swizzler<0, 1, 3, 0> xywx;
inline constexpr swizzler<0, 1, 3, 1> xywy;
inline constexpr swizzler<0, 1, 3, 2> xywz;
inline constexpr swizzler<0, 1, 3, 3> xyww;
inline constexpr swizzler<0, 2, 0, 0> xzxx;
inline constexpr swizzler<0, 2, 0, 1> xzxy;
inline constexpr swizzler<0, 2, 0, 2> xzxz;
inline constexpr swizzler<0, 2, 0, 3> xzxw;
inline constexpr swizzler<0, 2, 1, 0> xzyx;
inline constexpr swizzler<0, 2, 1, 1> xzyy;
inline constexpr swizzler<0, 2, 1, 2> xzyz;
inline constexpr swizzler<0, 2, 1, 3> xzyw;
inline constexpr swizzler<0, 2, 2, 0> xzzx;
inline constexpr swizzler<0, 2, 2, 1> xzzy;
inline constexpr swizzler<0, 2, 2, 2> xzzz;
inline constexpr swizzler<0, 2, 2, 3> xzzw;
inline constexpr swizzler<0, 2, 3, 0> xzwx;
inline constexpr swizzler<0, 2, 3, 1> xzwy;
inline constexpr swizzler<0, 2, 3, 2> xzwz;
inline constexpr swizzler<0, 2, 3, 3> xzww;
inline constexpr swizzler<0, 3, 0, 0> xwxx;
inline constexpr swizzler<0, 3, 0, 1> xwxy;
inline constexpr swizzler<0, 3, 0, 2> xwxz;
inline constexpr swizzler<0, 3, 0, 3> xwxw;
inline constexpr swizzler<0, 3, 1, 0> xwyx;
inline constexpr swizzler<0, 3, 1, 1> xwyy;
inline constexpr swizzler<0, 3, 1, 2> xwyz;
inline constexpr swizzler<0, 3, 1, 3> xwyw;
inline constexpr swizzler<0, 3, 2, 0> xwzx;
inline constexpr swizzler<0, 3, 2, 1> xwzy;
inline constexpr swizzler<0, 3, 2, 2> xwzz;
inline constexpr swizzler<0, 3, 2, 3> xwzw;
inline constexpr swizzler<0, 3, 3, 0> xwwx;
inline constexpr swizzler<0, 3, 3, 1> xwwy;
inline constexpr swizzler<0, 3, 3, 2> xwwz;
inline constexpr swizzler<0, 3, 3, 3> xwww;
inline constexpr swizzler<1, 0, 0, 0> yxxx;
inline constexpr swizzler<1, 0, 0, 1> yxxy;
inline constexpr swizzler<1, 0, 0, 2> yxxz;
inline constexpr swizzler<1, 0, 0, 3> yxxw;
inline constexpr swizzler<1, 0, 1, 0> yxyx;
inline constexpr swizzler<1, 0, 1, 1> yxyy;
inline constexpr swizzler<1, 0, 1, 2> yxyz;
inline constexpr swizzler<1, 0, 1, 3> yxyw;
inline constexpr swizzler<1, 0, 2, 0> yxzx;
inline constexpr swizzler<1, 0, 2, 1> yxzy;
inline constexpr swizzler<1, 0, 2, 2> yxzz;
inline constexpr swizzler<1, 0, 2, 3> yxzw;
inline constexpr swizzler<1, 0, 3, 0> yxwx;
inline constexpr swizzler<1, 0, 3, 1> yxwy;
inline constexpr swizzler<1, 0, 3, 2> yxwz;
inline constexpr swizzler<1, 0, 3, 3> yxww;
inline constexpr swizzler<1, 1, 0, 0> yyxx;
inline constexpr swizzler<1, 1, 0, 1> yyxy;
inline constexpr swizzler<1, 1, 0, 2> yyxz;
inline constexpr swizzler<1, 1, 0, 3> yyxw;
inline constexpr swizzler<1, 1, 1, 0> yyyx;
inline constexpr swizzler<1, 1, 1, 1> yyyy;
inline constexpr swizzler<1, 1, 1, 2> yyyz;
inline constexpr swizzler<1, 1, 1, 3> yyyw;
inline constexpr swizzler<1, 1, 2, 0> yyzx;
inline constexpr swizzler<1, 1, 2, 1> yyzy;
inline constexpr swizzler<1, 1, 2, 2> yyzz;
inline constexpr swizzler<1, 1, 2, 3> yyzw;
inline constexpr swizzler<1, 1, 3, 0> yywx;
inline constexpr swizzler<1, 1, 3, 1> yywy;
inline constexpr swizzler<1, 1, 3, 2> yywz;
inline constexpr swizzler<1, 1, 3, 3> yyww;
inline constexpr swizzler<1, 2, 0, 0> yzxx;
inline constexpr swizzler<1, 2, 0, 1> yzxy;
inline constexpr swizzler<1, 2, 0, 2> yzxz;
inline constexpr swizzler<1, 2, 0, 3> yzxw;
inline constexpr swizzler<1, 2, 1, 0> yzyx;
inline constexpr swizzler<1, 2, 1, 1> yzyy;
inline constexpr swizzler<1, 2, 1, 2> yzyz;
inline constexpr swizzler<1, 2, 1, 3> yzyw;
inline constexpr swizzler<1, 2, 2, 0> yzzx;
inline constexpr swizzler<1, 2, 2, 1> yzzy;
inline constexpr swizzler<1, 2, 2, 2> yzzz;
inline constexpr swizzler<1, 2, 2, 3> yzzw;
inline constexpr swizzler<1, 2, 3, 0> yzwx;
inline constexpr swizzler<1, 2, 3, 1> yzwy;
inline constexpr swizzler<1, 2, 3, 2> yzwz;
inline constexpr swizzler<1, 2, 3, 3> yzww;
inline constexpr swizzler<1, 3, 0, 0> ywxx;
inline constexpr swizzler<1, 3, 0, 1> ywxy;
inline constexpr swizzler<1, 3, 0, 2> ywxz;
inline constexpr swizzler<1, 3, 0, 3> ywxw;
inline constexpr swizzler<1, 3, 1, 0> ywyx;
inline constexpr swizzler<1, 3, 1, 1> ywyy;
inline constexpr swizzler<1, 3, 1, 2> ywyz;
inline constexpr swizzler<1, 3, 1, 3> ywyw;
inline constexpr swizzler<1, 3, 2, 0> ywzx;
inline constexpr swizzler<1, 3, 2, 1> ywzy;
inline constexpr swizzler<1, 3, 2, 2> ywzz;
inline constexpr swizzler<1, 3, 2, 3> ywzw;
inline constexpr swizzler<1, 3, 3, 0> ywwx;
inline constexpr swizzler<1, 3, 3, 1> ywwy;
inline constexpr swizzler<1, 3, 3, 2> ywwz;
inline constexpr swizzler<1, 3, 3, 3> ywww;
inline constexpr swizzler<2, 0, 0, 0> zxxx;
inline constexpr swizzler<2, 0, 0, 1> zxxy;
inline constexpr swizzler<2, 0, 0, 2> zxxz;
inline constexpr swizzler<2, 0, 0, 3> zxxw;
inline constexpr swizzler<2, 0, 1, 0> zxyx;
inline constexpr swizzler<2, 0, 1, 1> zxyy;
inline constexpr swizzler<2, 0, 1, 2> zxyz;
inline constexpr swizzler<2, 0, 1, 3> zxyw;
inline constexpr swizzler<2, 0, 2, 0> zxzx;
inline constexpr swizzler<2, 0, 2, 1> zxzy;
inline constexpr swizzler<2, 0, 2, 2> zxzz;
inline constexpr swizzler<2, 0, 2, 3> zxzw;
inline constexpr swizzler<2, 0, 3, 0> zxwx;
inline constexpr swizzler<2, 0, 3, 1> zxwy;
inline constexpr swizzler<2, 0, 3, 2> zxwz;
inline constexpr swizzler<2, 0, 3, 3> zxww;
inline constexpr swizzler<2, 1, 0, 0> zyxx;
inline constexpr swizzler<2, 1, 0, 1> zyxy;
inline constexpr swizzler<2, 1, 0, 2> zyxz;
inline constexpr swizzler<2, 1, 0, 3> zyxw;
inline constexpr swizzler<2, 1, 1, 0> zyyx;
inline constexpr swizzler<2, 1, 1, 1> zyyy;
inline constexpr swizzler<2, 1, 1, 2> zyyz;
inline constexpr swizzler<2, 1, 1, 3> zyyw;
inline constexpr swizzler<2, 1, 2, 0> zyzx;
inline constexpr swizzler<2, 1, 2, 1> zyzy;
inline constexpr swizzler<2, 1, 2, 2> zyzz;
inline constexpr swizzler<2, 1, 2, 3> zyzw;
inline constexpr swizzler<2, 1, 3, 0> zywx;
inline constexpr swizzler<2, 1, 3, 1> zywy;
inline constexpr swizzler<2, 1, 3, 2> zywz;
inline constexpr swizzler<2, 1, 3, 3> zyww;
inline constexpr swizzler<2, 2, 0, 0> zzxx;
inline constexpr swizzler<2, 2, 0, 1> zzxy;
inline constexpr swizzler<2, 2, 0, 2> zzxz;
inline constexpr swizzler<2, 2, 0, 3> zzxw;
inline constexpr swizzler<2, 2, 1, 0> zzyx;
inline constexpr swizzler<2, 2, 1, 1> zzyy;
inline constexpr swizzler<2, 2, 1, 2> zzyz;
inline constexpr swizzler<2, 2, 1, 3> zzyw;
inline constexpr swizzler<2, 2, 2, 0> zzzx;
inline constexpr swizzler<2, 2, 2, 1> zzzy;
inline constexpr swizzler<2, 2, 2, 2> zzzz;
inline constexpr swizzler<2, 2, 2, 3> zzzw;
inline constexpr swizzler<2, 2, 3, 0> zzwx;
inline constexpr swizzler<2, 2, 3, 1> zzwy;
inline constexpr swizzler<2, 2, 3, 2> zzwz;
inline constexpr swizzler<2, 2, 3, 3> zzww;
inline constexpr swizzler<2, 3, 0, 0> zwxx;
inline constexpr swizzler<2, 3, 0, 1> zwxy;
inline constexpr swizzler<2, 3, 0, 2> zwxz;
inline constexpr swizzler<2, 3, 0, 3> zwxw;
inline constexpr swizzler<2, 3, 1, 0> zwyx;
inline constexpr swizzler<2, 3, 1, 1> zwyy;
inline constexpr swizzler<2, 3, 1, 2> zwyz;
inline constexpr swizzler<2, 3, 1, 3> zwyw;
inline constexpr swizzler<2, 3, 2, 0> zwzx;
inline constexpr swizzler<2, 3, 2, 1> zwzy;
inline constexpr swizzler<2, 3, 2, 2> zwzz;
inline constexpr swizzler<2, 3, 2, 3> zwzw;
inline constexpr swizzler<2, 3, 3, 0> zwwx;
inline constexpr swizzler<2, 3, 3, 1> zwwy;
inline constexpr swizzler<2, 3, 3, 2> zwwz;
inline constexpr swizzler<2, 3, 3, 3> zwww;
inline constexpr swizzler<3, 0, 0, 0> wxxx;
inline constexpr swizzler<3, 0, 0, 1> wxxy;
inline constexpr swizzler<3, 0, 0, 2> wxxz;
inline constexpr swizzler<3, 0, 0, 3> wxxw;
inline constexpr swizzler<3, 0, 1, 0> wxyx;
inline constexpr swizzler<3, 0, 1, 1> wxyy;
inline constexpr swizzler<3, 0, 1, 2> wxyz;
inline constexpr swizzler<3, 0, 1, 3> wxyw;
inline constexpr swizzler<3, 0, 2, 0> wxzx;
inline constexpr swizzler<3, 0, 2, 1> wxzy;
inline constexpr swizzler<3, 0, 2, 2> wxzz;
inline constexpr swizzler<3, 0, 2, 3> wxzw;
inline constexpr swizzler<3, 0, 3, 0> wxwx;
inline constexpr swizzler<3, 0, 3, 1> wxwy;
inline constexpr swizzler<3, 0, 3, 2> wxwz;
inline constexpr swizzler<3, 0, 3, 3> wxww;
inline constexpr swizzler<3, 1, 0, 0> wyxx;
inline constexpr swizzler<3, 1, 0, 1> wyxy;
inline constexpr swizzler<3, 1, 0, 2> wyxz;
inline constexpr swizzler<3, 1, 0, 3> wyxw;
inline constexpr swizzler<3, 1, 1, 0> wyyx;
inline constexpr swizzler<3, 1, 1, 1> wyyy;
inline constexpr swizzler<3, 1, 1, 2> wyyz;
inline constexpr swizzler<3, 1, 1, 3> wyyw;
inline constexpr swizzler<3, 1, 2, 0> wyzx;
inline constexpr swizzler<3, 1, 2, 1> wyzy;
inline constexpr swizzler<3, 1, 2, 2> wyzz;
inline constexpr swizzler<3, 1, 2, 3> wyzw;
inline constexpr swizzler<3, 1, 3, 0> wywx;
inline constexpr swizzler<3, 1, 3, 1> wywy;
inline constexpr swizzler<3, 1, 3, 2> wywz;
inline constexpr swizzler<3, 1, 3, 3> wyww;
inline constexpr swizzler<3, 2, 0, 0> wzxx;
inline constexpr swizzler<3, 2, 0, 1> wzxy;
inline constexpr swizzler<3, 2, 0, 2> wzxz;
inline constexpr swizzler<3, 2, 0, 3> wzxw;
inline constexpr swizzler<3, 2, 1, 0> wzyx;
inline constexpr swizzler<3, 2, 1, 1> wzyy;
inline constexpr swizzler<3, 2, 1, 2> wzyz;
inline constexpr swizzler<3, 2, 1, 3> wzyw;
inline constexpr swizzler<3, 2, 2, 0> wzzx;
inline constexpr swizzler<3, 2, 2, 1> wzzy;
inline constexpr swizzler<3, 2, 2, 2> wzzz;
inline constexpr swizzler<3, 2, 2, 3> wzzw;
inline constexpr swizzler<3, 2, 3, 0> wzwx;
inline constexpr swizzler<3, 2, 3, 1> wzwy;
inline constexpr swizzler<3, 2, 3, 2> wzwz;
inline constexpr swizzler<3, 2, 3, 3> wzww;
inline constexpr swizzler<3, 3, 0, 0> wwxx;
inline constexpr swizzler<3, 3, 0, 1> wwxy;
inline constexpr swizzler<3, 3, 0, 2> wwxz;
inline constexpr swizzler<3, 3, 0, 3> wwxw;
inline constexpr swizzler<3, 3, 1, 0> wwyx;
inline constexpr swizzler<3, 3, 1, 1> wwyy;
inline constexpr swizzler<3, 3, 1, 2> wwyz;
inline constexpr swizzler<3, 3, 1, 3> wwyw;
inline constexpr swizzler<3, 3, 2, 0> wwzx;
inline constexpr swizzler<3, 3, 2, 1> wwzy;
inline constexpr swizzler<3, 3, 2, 2> wwzz;
inline constexpr swizzler<3, 3, 2, 3> wwzw;
inline constexpr swizzler<3, 3, 3, 0> wwwx;
inline constexpr swizzler<3, 3, 3, 1> wwwy;
inline constexpr swizzler<3, 3, 3, 2> wwwz;
inline constexpr swizzler<3, 3, 3, 3> wwww;
}
