#pragma once

#include "ball.hh"
#include "aabb.hh"
#include "cylinder.hh"
#include "disk.hh"
#include "frustum.hh"
#include "line.hh"
#include "plane.hh"
#include "polygon.hh"
#include "polyline.hh"
#include "ray.hh"
#include "segment.hh"
#include "sphere.hh"
#include "triangle.hh"
#include "tube.hh"
