#pragma once

#include <typed-geometry/functions/aabb.hh>
#include <typed-geometry/functions/angle.hh>
#include <typed-geometry/functions/area.hh>
#include <typed-geometry/functions/bounds.hh>
#include <typed-geometry/functions/centroid.hh>
#include <typed-geometry/functions/closest_points.hh>
#include <typed-geometry/functions/contains.hh>
#include <typed-geometry/functions/coordinates.hh>
#include <typed-geometry/functions/cross.hh>
#include <typed-geometry/functions/data_ptr.hh>
#include <typed-geometry/functions/determinant.hh>
#include <typed-geometry/functions/diag.hh>
#include <typed-geometry/functions/direction.hh>
#include <typed-geometry/functions/distance.hh>
#include <typed-geometry/functions/dot.hh>
#include <typed-geometry/functions/gaussian.hh>
#include <typed-geometry/functions/interpolate.hh>
#include <typed-geometry/functions/intersection.hh>
#include <typed-geometry/functions/inverse.hh>
#include <typed-geometry/functions/length.hh>
#include <typed-geometry/functions/look_at.hh>
#include <typed-geometry/functions/math.hh>
#include <typed-geometry/functions/minmax.hh>
#include <typed-geometry/functions/mix.hh>
#include <typed-geometry/functions/norm.hh>
#include <typed-geometry/functions/normal.hh>
#include <typed-geometry/functions/normalize.hh>
#include <typed-geometry/functions/orthographic.hh>
#include <typed-geometry/functions/outer_product.hh>
#include <typed-geometry/functions/perimeter.hh>
#include <typed-geometry/functions/perpendicular.hh>
#include <typed-geometry/functions/perspective.hh>
#include <typed-geometry/functions/predicates.hh>
#include <typed-geometry/functions/project.hh>
#include <typed-geometry/functions/quadrics.hh>
#include <typed-geometry/functions/random_choice.hh>
#include <typed-geometry/functions/rasterize.hh>
#include <typed-geometry/functions/reflect.hh>
#include <typed-geometry/functions/refract.hh>
#include <typed-geometry/functions/rotation.hh>
#include <typed-geometry/functions/scaling.hh>
#include <typed-geometry/functions/size.hh>
#include <typed-geometry/functions/smoothstep.hh>
#include <typed-geometry/functions/statistics.hh>
#include <typed-geometry/functions/submatrix.hh>
#include <typed-geometry/functions/subvector.hh>
#include <typed-geometry/functions/tangent.hh>
#include <typed-geometry/functions/translation.hh>
#include <typed-geometry/functions/uniform.hh>
#include <typed-geometry/functions/volume.hh>
